// alert types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// auth types
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// module types
export const GET_MODULES = 'GET_MODULES';
export const MODULE_ERROR = 'MODULE_ERROR';
export const CONFIRM_MODULES = 'CONFIRM_MODULES';
export const CLEAR_MODULES = 'CLEAR_MODULES';
export const ADD_MODULES = 'ADD_MODULES';
export const DELETE_MODULE = 'DELETE_MODULE';
export const UPDATE_RANKINGS = 'UPDATE_RANKINGS';
export const SET_CURRENT_MODULES = 'SET_CURRENT_MODULES';
export const CLEAR_CURRENT_MODULES = 'CLEAR_CURRENT_MODULES';
export const SET_DISPLAYED_MODULES = 'SET_DISPLAYED_MODULES';
// search types
export const FILTER_MODULES = 'FILTER_MODULES';
export const FILTER_BY_TIME = 'FILTER_BY_TIME';
export const FILTER_ERROR = 'FILTER_ERROR';
export const ADD_TIME_FILTER = 'ADD_TIME_FILTER';
export const DELETE_TIME_FILTER = 'DELETE_TIME_FILTER';
export const CLEAR_TIME_FILTER_BY_DAY = 'CLEAR_TIME_FILTER_BY_DAY';
export const CLEAR_ALL_TIME_FILTERS = 'CLEAR_ALL_TIME_FILTERS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ADD_SELECTION = 'ADD_SELECTION';
export const DELETE_SELECTION = 'DELETE_SELECTION';
export const CLEARALL_SELECTION = 'CLEAR_SELECTION';
export const IS_SEARCHED_FALSE = 'IS_SEARCHED_FALSE';
export const IS_SEARCHED_TRUE = 'IS_SEARCHED_TRUE';
// layout types
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
// map types
export const SET_COORDS = 'SET_COORDS';
export const SET_FIRST_LOCATION = 'SET_FIRST_LOCATION';
export const SET_SECOND_LOCATION = 'SET_SECOND_LOCATION';
export const SET_DAY = 'SET_DAY';
export const GET_BUS_STOPS = 'GET_BUS_STOPS';
export const SET_FIRST_NEAREST = 'SET_FIRST_NEAREST';
export const SET_SECOND_NEAREST = 'SET_SECOND_NEAREST';
export const SET_LOADED = 'SET_LOADED';
// modalert types
export const SET_CONFLICT = 'SET_CONFLICT';
export const REMOVE_CONFLICT = 'REMOVE_CONFLICT';
export const GET_CONFLICTS = 'GET_CONFLICTS';
